server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:samsungprojectdb
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
